## Flutter wrapper
-dontwarn io.flutter.embedding.**
-dontwarn android.**
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class kotlin.Metadata { *; }
-dontnote kotlin.internal.**
-dontnote kotlin.reflect.jvm.internal.**